### ISSUE TITLE
Add JAX backend

### ISSUE THREAD

**Issue by oleg-kachan** [pymanopt/pymanopt#107]
Requesting the addition of [JAX](https://github.com/google/jax) backend.

**Comment by nkoep** [comment]
I'd like to fix more pressing, fundamental issues such as #23 first (see also #106 for why it's not fixed yet) before adding more backends. It's definitely on my list though considering that jax supercedes autograd now.

**Comment by j-towns** [comment]
Note the JAX API is near-identical to the Autograd API (at least as far as Pymanopt would be concerned), so it should be fairly trivial to implement at least basic support.

**Comment by oleg-kachan** [comment]
@nkoep @j-towns 
I'd like to take care of this issue if I explained the steps it requires to take.

Could you provide an outline?

**Comment by j-towns** [comment]
The backend handling stuff resides in https://github.com/pymanopt/pymanopt/tree/master/pymanopt/autodiff/backends. Since JAX is so similar to Autograd, I would start by duplicating https://github.com/pymanopt/pymanopt/blob/master/pymanopt/autodiff/backends/_autograd.py and switching over all of the mappings in there to the appropriate JAX functions.

**Comment by mraveri** [comment]
Needed Jax interface and started implementing it. Opened a wip PR #115  
Two tests are failing though...

**Comment by sweichwald** [comment]
Thanks! Closing this for now – refer to the WIP PR #115.
Looking forward to catching up with it as/when time permits.
