### ISSUE TITLE
descent direction in steepest descent solver

### ISSUE THREAD

**Issue by 2860166** [pymanopt/pymanopt#108]
In the matlab implementation, the lincomb function is used to calculate the descent direction, for instance `desc_dir = problem.M.lincomb(newx, -1, grad)`. but in your implementation, you simply use `desc_dir =-grad`. do they have same results?
what about if I want to calculate the addition of 2 tangent vector? do I need to implement lincomb function or I can simply add them by + operator (vec_a+vec_b)?
thank you.

Hadi

**Comment by kellertuer** [comment]
Yes, both implementations do the same. The Matlab variant says: take the linear combination in the tangent space of `newx` of `grad` with factor `-1` (see https://www.manopt.org/tutorial.html#manifolds ). In short that is exactely `desc_dir=-grad`.

Since the gradient is usually represented in an array representing the elements from the tangent space, usually just `+` should suffice, but note that for example for fixed rank matrices, you have to use the corresponding type, see at the last lines of https://github.com/pymanopt/pymanopt/blob/master/pymanopt/manifolds/fixed_rank.py

**Comment by 2860166** [comment]
thank you very much @kellertuer
