### ISSUE TITLE
problem with pymanopt.function.Autograd

### ISSUE THREAD

**Issue by loik77360** [pymanopt/pymanopt#171]
I have a problem with the python library pymanopt. 
I don’t know why this line doesn’t work on my machine:
" @pymanopt.function.Autograd(manifold) "
The error says that function.Autograd doesn’t exist and I am using the latest version of the library 0.2.5. 
I used the same code as the one on the website https://pymanopt.org/docs/latest/quickstart.html

**Comment by nkoep** [comment]
Hi :wave: Sorry for the late reply. Unfortunately this is due to the fact that the documentation is ahead of the latest version on pypi. Since we're overhauling the API of pymanopt we currently only provide up-to-date docs for the version on master. You can try installing the dev version with `pip install --no-use-pep517 git+https://github.com/pymanopt/pymanopt` from master directly though for now until version 1.0 is released.
