### ISSUE TITLE
The difference about the dimension of vector in tangent space.

### ISSUE THREAD

**Issue by CodingCatMountain** [pymanopt/pymanopt#242]
Hi, Thanks you for the development! I wanna to ask a question about the dimension about the dimension of vector in tangent space. Since I am graduate about Robotics, the manifold I concerned most is S^3 manifold ( for unit quaternion). However, in the past I always think the dimension of vector in tanget space of S^3 manifold is 3, and the dimension of vector in tangent space of S^2 manifold (the sphere in 3D space) is 2, so I try to use `S2 = Sphere(3); S2.exp(x1, v1)`, where `x1` is a point on sphere in 3D space, and `v1` is the tangent vector, and I think the dimension of `v1` should be 2. But the error is met: _ValueError: operands could not be broadcast together with shapes (3,) (2,)_ . May I ask why would it happen? How should I convert the dimension from 2 to 3 in order to utilize pymanopt?

**Comment by CodingCatMountain** [comment]
The most reference paper that I read : [GMM on Riemannian Manifold](https://ora.ox.ac.uk/objects/uuid:d580f7ea-476d-4a0c-a39a-2a000a91717d/download_file?file_format=pdf&safe_filename=An%2BApproach%2Bfor%2BImitation%2BLearning%2Bon%2BRiemannian%2BManifolds.pdf&type_of_work=Journal+article). In the table 1 in this paper, the ``Log_{e}(g) \in R^2 , g\in S^2``.

**Comment by kellertuer** [comment]
Hi,
that table is a bit too condensed to get the information. Compared to that I can explain the scenario and probably, where your error is. But let's take the Sphere because it is easier to imaging.

The sphere `S2=Sphere(3)` in pymanopt refers to the unit sphere in R3, which – you are correct – has dimension 2 (the 3 here refers to the shape of the vectors). So we _represent_ points on `S2` as unit vectors in R3.
(We could also use Euler angles and actually have something that has just 2 values, but that would be a mess numerically).

Now imagine the geometrical tangent plane at the North Pole. It is the plane parallel to the xy-plane but at z=1 (i.e. it touches the sphere at the point p=(0,0,1)). The point where this plane touches p we call 0 and any vector in the plane should be considered as a vector pointing from this zero into the plane. In other words any `v=(a,b,0)` is fine (note that the tangent space is always orthogonal to p, so here I chose an easy point to illustrate).
Sure just having `a,b` in mind we have something 2-dimensional (it is a _plane_ nonetheless). But similar to preferring to represent the points p of our 2D manifold `S2` as (unit) points in R3, it is usually easier to represent our tangent vectors in the form of `v` (especially for non-northpole-points we will have a 2D plane in a more complicated format for the `v`s.

To in summary
* the sphere is 2-dimensional, but we represent its points `p` as unit vectors (something 3D but with a restriction on the norm they form a 2D space – the surface of the sphere)
* similarly, the tangent space for a fixed point `p` are all vectors `v` in R3 such that `⟨p,v⟩=0`. This is a plane and hence something 2D _but_ similar to the unit vectors we prefer to use something in the embedding R3 to describe them (shortest reason: computing with these is cool).

**Comment by CodingCatMountain** [comment]
@kellertuer Thank You, Kellertuer. Due to your explanation is so great,  I understand how should I modified my code. May be just expand the tangent vector `v1` to `(a,b,0)`, Right? And I think I know why pymanopt choose to represent the tangent vector in S^2 with 3-dimension vector, because **"especially for non-northpole-points we will have a 2D plane in a more complicated format for the vs"** which you mentioned.

**Comment by kellertuer** [comment]
No, just always taking vectors of the form `(a,b,0)` would not work for arbitrary points. for any values of a and b this would only be tangent vectors if the point p you are at is either the north or the south pole (`p=(0,0,±1)`). Depending on the point you are at you have to choose vectors `v` that fulfil `<p,v> = 0`, i.e. p and v have to be orthogonal.

**Comment by CodingCatMountain** [comment]
@kellertuer , I have to apologize that I didn't express my points clearly. In robotics, we always "project" the point on manifold, i.e. SO(3) and S^3, into the tangent space of identity element and I think it is Lie Algebra mentioned in some textbooks. Then I think the API: `sphere.transport() `could be utilized to parallel transport the vector in the tangent space of identity element to the tangent space of another point on manifold. Thank you again for pointing our my mistake.

**Comment by kellertuer** [comment]
Yes, but on SO(3) you have a Lie algebra so identifying all tangent spaces with the Lie algebra is what is correct and usually done for simplicity.
On the Sphere this is not available (still conceptually thinking in the North Pole often helps a bit).

Great that it was just slightly incorrect formulation, because that means you understood the concept 👍

**Comment by CodingCatMountain** [comment]
> On the Sphere this is not available (still conceptually thinking in the North Pole often helps a bit).  
@kellertuer Thank you, Kellertuer. May I ask about what do you mean with this sentence? DO you mean that it is wrong to "project" any point on S^3 or S^2 to the tangent space of North Pole then utilize to ``sphere.transport()`` the tangent vector to the tangent space of other point on S^3 or S^2?

**Comment by kellertuer** [comment]
That depends on what you want. Projection on T_NS^2 yields a tangent vector at the North Pole N for sure. (Parallel) transporting it to some point yields a tangent vector there, sure.
But if you do that _always_ (more to N do computations, move back) that is too much effort.
Compared to SO(3) where all tangent spaces can be identified with so(3) because we have the Lie algebra.

Instead if you have an arbitrary vector in R3 and want its “tangent part at p” project onto TpS2

**Comment by CodingCatMountain** [comment]
@kellertuer Thank you, kellertuer. I do learn a lot from you.
