### ISSUE TITLE
R+ manifold

### ISSUE THREAD

**Issue by LarsDoorenbos** [pymanopt/pymanopt#243]
Hey,

Thank you for the great repository. 
I am implementing the method of a paper where they mention using PyManOpt to optimize over the product of 2 manifolds $\mathbb{S}^{n-1} \times \mathbb{R}^+$ (i.e., a hypersphere with n-1 dimensions and the set of positive real numbers). I understand how to do the hypersphere, but for the positive real numbers, I am probably missing something obvious. How do I enforce this? Can I enforce this constraint with the Euclidean manifold somehow? Or should I use a different manifold for it? 

Thanks!

**Comment by kellertuer** [comment]
Constraint Rn would give you the wrong geometry you could easily “run off” the manifold.

There is a trick – where I am not experienced in Python enough (Julia person here) to tell whether that will just be numbers or 1-element arrays:

Consider the Symmetric Positive Definite Matrices, i.e. all A (n-by-n) with x^TAx > 0 for all vectors x in Rn that are not the zero vector.
If you now set n=1 A is a 1-by-1 matrix – commonly known as a number. But since then x is also just a number we get the constraint xAx = Ax^2, which is > 0 for x != 0 if and only if A > 0.

So while (depending on Python) it might not be positive numbers, it would be element-wise-positive 1-element vectors. Which of course are hence positive numbers, just stored differently.

**Comment by LarsDoorenbos** [comment]
Great! I'll give that a try, and close the issue when I get it work; thank you!
