### ISSUE TITLE
Error in jax tests

### ISSUE THREAD

**Issue by antoinecollas** [pymanopt/pymanopt#260]
Tests are not running anymore because `config` cannot be imported from `jax.config` with the latest version of `jax`.
This is likely due to https://github.com/google/jax/pull/19895 .
Libraries relying on `pymanopt` cannot update `jax` because of this. See https://github.com/PythonOT/POT/issues/609

**Comment by ghbrown** [comment]
I see that this has been fixed by #261, at least on main (awesome).
Would it be possible to make another release or otherwise update the public package on PYPI?

I consider this a relatively major fix since `pymanopt` does not have a maximum `jax(lib)` version; this means a basic `pymanopt` + `jax` install from PYPI is currently non-functional.

**Comment by NicolasBoumal** [comment]
This should be fixed with release 2.2.1, now reflected on pypi.
