### ISSUE TITLE
Geodesic on Stiefel Manifold

### ISSUE THREAD

**Issue by Fengcheng-Pei** [pymanopt/pymanopt#276]
Hi,

If A is a fix point on a Stiefel manifold, and how could I get a geodesic from an arbitrary point X on the manifold to this point A? Is it possible to find a closed form representation?

Best regards,
Fengcheng Pei

**Comment by kellertuer** [comment]
Hi,

as far as I am aware, there is no closed form solution. You could for example compute this as soon as you have log and exp available, but then there is for example https://arxiv.org/pdf/1604.05054 talking about an iterative algorithm for the log. Concretely for geodesics there is also this paper https://arxiv.org/pdf/2105.07017 that at least talks about efficient computations of quasi geodesics. So to me that looks like. there is no closed form known.

**Comment by kellertuer** [comment]
Well, you can also start from know (locally) convex functions. Globally there is not much hope for a (non-constant) convex function due to positive curvature.  

One function that is convex (locally) is: Fix a point A on Stiefel and take f(B) = dist°2(A,B) at least for B close enough (see for example this paper https://arxiv.org/pdf/2403.03782 about the injectivity radius), where dust is the squared distance (with respect to the metric you chose).

**Comment by NicolasBoumal** [comment]
Thanks for your input @kellertuer; closing now at it is not a pymanopt issue.
