### ISSUE TITLE
user defined gradient

### ISSUE THREAD

**Issue by raminammour** [pymanopt/pymanopt#38]
Hello,

I define my gradient (I usually cannot use automatic differentiation for problems I am interested in), but I still get an error because of a missing backend. Can you help with bypassing automatic differentiation:

```python
def cost(X):
    return (X[0]-0.5)**2+X[1]**2

def egrad(X):
    return [2*(X[0]-0.5),2*X[1]]

M=Euclidean(2)

Solver=ConjugateGradient()
problem = Problem(manifold=M, cost=cost,grad=egrad, egrad=egrad,verbosity=2)
xoptimal = Solver.solve(problem,x=[10,10])

Compiling cost function...
...
ValueError: Cannot determine autodiff backend from cost function of type `function`. Available backends are: 
```

Thanks!

**Comment by j-towns** [comment]
Hi there. Firstly, Pymanopt works with [numpy](http://www.numpy.org) arrays. On the line
```python
xoptimal = Solver.solve(problem,x=[10,10])
```
`[10, 10]` is a list. You need to do create a numpy array with those values, something like
```python
import numpy as np
...
xoptimal = Solver.solve(problem,x=np.array([10,10]))
```

Your `egrad` function is also returning a list, and this should be a numpy array. This can be easily fixed by changing the line
```python
    return [2*(X[0]-0.5),2*X[1]]
```
to
```python
    return np.array([2*(X[0]-0.5),2*X[1]])
```

You only need to specify the `grad` kwarg of `Problem`, not the `egrad`. So the whole code:

```python
import numpy as np

from pymanopt.manifolds import Euclidean
from pymanopt.solvers import ConjugateGradient
from pymanopt import Problem

def cost(X):
    return (X[0]-0.5)**2+X[1]**2

def grad(X):
    return np.array([2*(X[0]-0.5),2*X[1]])

M = Euclidean(2)

Solver = ConjugateGradient()
problem = Problem(manifold=M, cost=cost, grad=grad, verbosity=2)
xoptimal = Solver.solve(problem, x=np.array([10,10]))
```
should work.

Two questions:
1. Are you using manifolds other than Euclidean? If not then you might be better off using [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize).
2. Out of curiosity, which problems are you working on where you can't use automatic differentiation?

**Comment by raminammour** [comment]
Hey,

The code above still produces the same error, maybe because I don't have any of the backends installed?

`ValueError: Cannot determine autodiff backend from cost function of type `function`. Available backends are:` 

1. I will be using other manifolds, this code was a minimal code reproducing the error.
2. I am interested in PDE constrained optimization. Strictly speaking, you can use autodiff (it needs to be quite sophisticated though), but sometimes the code produced is not as efficient as the manually written code.

Thanks for the help!

**Comment by raminammour** [comment]
Confirmed, still looks for backend even if the gradient is defined. I installed `autograd` but didn't use it, it works.

Maybe it is best to skip the backend lookup step if user provides grad/hess.

Thanks again!

**Comment by sweichwald** [comment]
I would expect it to work when changing Jamie's example to the following:

```python
problem = Problem(manifold=M, cost=cost, egrad=grad, verbosity=2)
```
Note that this sets the Euclidean gradient `egrad` but not `grad`.

If above doesn't work, I agree with the suggested fix: No backend check if no backend needed.

(Sorry, since I currently don't have access to a computer, I couldn't test it.)

**Comment by raminammour** [comment]
Still looks for backend and exits with error. Thankfully, this one should be easy to fix :)
