### ISSUE TITLE
Tensorflow: lacking variable initialization

### ISSUE THREAD

**Issue by luk-f-a** [pymanopt/pymanopt#57]
Hello, first of all thanks for this amazing package.

I came across a problem while trying to use the tensorflow backend. I ran the regression example and all worked well. However, when I used my own code I got the following error:

> FailedPreconditionError (see above for traceback): Attempting to use uninitialized value f_1
	 [[Node: f_1/read = Identity[T=DT_DOUBLE, _class=["loc:@f_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](f_1)]]

I'm using pymanopt 0.2.3 (installed via pip), tensorflow 1.7.0 on python 3.6.

I found a quick fix which is to add, in the __init__ of the tensorflow backend a variable initialization step, as follows (last line):

```
class TensorflowBackend(Backend):
    def __init__(self):
        if tf is not None:
            self._session = tf.Session()
            self._session.run(tf.initialize_all_variables())
```

I can create a pull request if you want, but maybe for such a small thing you prefer to add it yourselves.

For reference, this is my cost function:

```
d = 4
p = 2
manifold = Stiefel(d, p)
A_0 = np.eye(d,p)
A_var = tf.Variable(A_0, name='a_var', dtype=tf.float64)
x = np.random.normal(size=(1000,d))
y = np.random.normal(size=(1000,))
W = tf.matmul(x, A_var)

f = tf.Variable(0, name='f', dtype=tf.float64)
for j in range(p):
    f = tf.add(tf.reduce_sum(y*W[:,j])**2, f)
cost = -(f)/n_observations**2

```

**Comment by luk-f-a** [comment]
Quick follow up: apparently I missed a deprecation warning and the new line should be

self._session.run(tf.global_variables_initializer()),

although I guess it depends which TF version you are targeting.

**Comment by sweichwald** [comment]
Thanks for raising this!

For reference a MWE built upon above example; yields a `FailedPreconditionError` since f is uninitialized in pymanopt's (autodiff backend) tensorflow session.

```python
import tensorflow as tf
import numpy as np

from pymanopt import Problem
from pymanopt.solvers import TrustRegions
from pymanopt.manifolds import Stiefel


## provided example (added n_observations)
d = 4
p = 2
manifold = Stiefel(d, p)
A_0 = np.eye(d,p)
A_var = tf.Variable(A_0, name='a_var', dtype=tf.float64)
x = np.random.normal(size=(1000,d))
y = np.random.normal(size=(1000,))
W = tf.matmul(x, A_var)
n_observations = 1000
f = tf.Variable(0, name='f', dtype=tf.float64)  # <-- uninitialized
for j in range(p):
    f = tf.add(tf.reduce_sum(y*W[:,j])**2, f)
cost = -(f)/n_observations**2
##

solver = TrustRegions()

problem = Problem(manifold=manifold, cost=cost, arg=A_var, verbosity=0)

solver.solve(problem)
```

---

Note, that the problem in above example is resolved by replacing
```python
f = tf.Variable(0, name='f', dtype=tf.float64)  # <-- uninitialized
```
by
```
f = tf.zeros(1, name='f', dtype=tf.float64)
```

---

While the proposed solution (cf. #58) works, I'm unsure whether (silently and) always globally initializing all variables is the best way to resolve the issue. The [TensorFlow wiki on initializing variables](https://www.tensorflow.org/programmers_guide/variables#initializing_variables) seems also to advocate explicit initialization.

I currently see two possible ways to deal with this:
1. Allow to pass a tensorflow session to the autodiff backend and let the user deal with the initialization of the variables in that session.
2. Transparently expose problem.backend._session so that users can run ops in the tensorflow session used by pymanopt's autodiff backend, e.g. in order to run the desired initializations etc.

As of now I have a slight preference for the latter, which would allow what is sketched in the example below and would ensure explicit initialization by the user.
This may also be relevant if we decide to more fundamentally rework the autodiff backend #55.

```python
import tensorflow as tf
import numpy as np

from pymanopt import Problem
from pymanopt.solvers import TrustRegions
from pymanopt.manifolds import Stiefel


## provided example (added n_observations)
d = 4
p = 2
manifold = Stiefel(d, p)
A_0 = np.eye(d,p)
A_var = tf.Variable(A_0, name='a_var', dtype=tf.float64)
x = np.random.normal(size=(1000,d))
y = np.random.normal(size=(1000,))
W = tf.matmul(x, A_var)
n_observations = 1000
f = tf.Variable(0, name='f', dtype=tf.float64)  # <-- uninitialized
for j in range(p):
    f = tf.add(tf.reduce_sum(y*W[:,j])**2, f)
cost = -(f)/n_observations**2
##

solver = TrustRegions()

problem = Problem(manifold=manifold, cost=cost, arg=A_var, verbosity=0)

problem.backend._session.run(tf.global_variables_initializer())  # <--

solver.solve(problem)
```

**Comment by sweichwald** [comment]
The transparent exposure of the backend tensorflow session may also be relevant for #59.

**Comment by luk-f-a** [comment]
I agree, this might better be solved by the exposure of the session. Going even further, I would say it would be useful to allow users to provide their own sessions. For example, I had the need to restrict the amount of threads TF could use, and for that I had to create my own session.

**Comment by nkoep** [comment]
See https://github.com/pymanopt/pymanopt/pull/58#issuecomment-580247295.
