### ISSUE TITLE
Optimizing over multiple manifolds

### ISSUE THREAD

**Issue by ahwillia** [pymanopt/pymanopt#68]
I'm interested in trying to fit the following model (Orthogonal CCA; see [Cunningham & Ghahramani, 2015](https://arxiv.org/pdf/1406.0873.pdf)).

![image](https://user-images.githubusercontent.com/636625/50575418-28793680-0dcd-11e9-8048-52a74479ddfa.png)

As specified above, both `M_a` and `M_b` are constrained to live the Stiefel manifold.

Is there a way for me to use this package to set up one optimization problem for this? Or would I need to set up two optimization problems (one for `M_a` and another for `M_b`) and then alternate between solving them until both variables converge?

**Comment by nkoep** [comment]
Hi! Yes, this is indeed possible by interpreting the pair `(M_a,M_b)` as an element of a product manifold. Have a look at the various `regression_offset_*.py` files in the examples directory. Those should be a good starting point for various autodiff backends.

**Comment by ahwillia** [comment]
Thank you this was very straightforward to implement!

**Comment by ghbrown** [comment]
At least at the time of writing this post, the best/only example I could find for optimizing over product manifolds was: `examples/notebooks/mixture_of_gaussians.py`.

`examples/regression_offset_*.py` no longer exist, and even if you dig them up from the git history a few critical things have changed since then.
