### ISSUE TITLE
Supporting multiple backends but using numpy in manifold implementations

### ISSUE THREAD

**Issue by calincru** [pymanopt/pymanopt#80]
One thing I'm confused about is the fact that despite the multiple-backend framework, the manifold properties are pretty useless if needed as part of the objective.  For instance, if I have an objective which computes distances between points on a manifold, I have to re-implement the distance function using the tensor types of my backend.  Do I miss something?

If that's the case, then I'm not so sure if the backend abstraction makes sense at all. The complexity of maintaining it is the same as having a full, separate manopt implementation for each one of them. Arguably, the former is even worse, due to the cost of abstraction.

**Comment by nkoep** [comment]
It's hard to argue with your point. We were actually bitten by this ourselves in our port of the Nelder-Mead solver since it requires computation of the Karcher mean. The easiest solution was to implement the subroutine with the callable backend (i.e., with an explicit numpy-based cost and gradient) since we can't make any assumptions on the availability of backends. Of course we could test for the presence of theano, say. However, this would arguably couple solver and backends even more tightly, which ideally should be completely independent.

That being said, I'd argue that the real benefit of pymanopt is that gradients and Hessians (ideally) never have to be worked out by hand. If that means a user has to port the distance function by hand, I think that's a small price to pay for the convenience of not having to do any calculus ;) You may disagree with this point, but as you also pointed out, there's really no point in maintaining essentially a different pymanopt version for each backend.
